# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cloning app
      uses: actions/checkout@v2
      with:
        repository: WASdev/sample.daytrader7
        path: sample.daytrader7
    - name: Cloning app
      uses: actions/checkout@v2
      with:
        repository: saud-aslam/trading-app
        path: trading-app
    - name: Moving apps
      run: mv sample.daytrader7 trading-app ../
    - name: Build & test with gradle
      working-directory: core
      run: ./gradlew test
    - name: Copying results
      run: cp core/transaction-* core/build/test-results/test
    - name: Upload Test Report
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: test results
        path: core/build/test-results/test
